# docker-compose.yml

services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    environment:
      - ROLE=controller
    ports:
      - "8000:8000"
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RAWIO

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    environment:
      - ROLE=collector
      - CONTROLLER_URL=http://controller:8000
    restart: unless-stopped
    privileged: true
    network_mode: host  # Critical for BLE/RF access on Linux
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      - "/dev/serial:/dev/serial"
    volumes:
      - /var/run/dbus:/var/run/dbus
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_RAWIO
