version: '3.8'
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    environment:
      - ROLE=controller
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./data:/app/data

  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    environment:
      - ROLE=collector
      - CONTROLLER_URL=http://127.0.0.1:8000
      - SCAN_INTERVAL=10
      - COLLECTION_TIMEOUT=5
    restart: unless-stopped
    network_mode: host
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - /var/run/dbus:/var/run/dbus
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
      - SYS_RAWIO
