site_name: "Project PEAK Documentation"
docs_dir: docs  # This tells MkDocs to look for markdown files in the inner docs directory (ProjectPEAK/docs/docs)

plugins:
  - search
  - mkdocstrings:
      default_handler: python
nav:
  - Home: index.md
  - API Reference:
      - Collector: collector.md
      - Controller: controller.md
